server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Rutas para los HTML (Para que el localStorage se comparta)
        - id: ms-seguridad-web
          uri: lb://MS-SEGURIDAD
          predicates:
            - Path=/login.html, /register.html

        - id: ms-catalogo-web
          uri: lb://MS-CATALOGO
          predicates:
            - Path=/catalogo.html, /producto.html

        - id: ms-carrito-web
          uri: lb://MS-CARRITO
          predicates:
            - Path=/carrito.html

        - id: ms-ventas-web
          uri: lb://MS-VENTAS
          predicates:
            - Path=/pedidos.html, /checkout.html

        - id: ms-citas-web
          uri: lb://MS-CITAS
          predicates:
            - Path=/citas.html, /sucursales.html, /mis-citas.html

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true