server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: seguridad-service
          uri: lb://ms-seguridad
          predicates:
            - Path=/api/seguridad/**
          filters:
            - StripPrefix=2

        - id: catalogo-service
          uri: lb://ms-catalogo
          predicates:
            - Path=/api/catalogo/**
          filters:
            - StripPrefix=2

        - id: carrito-service
          uri: lb://ms-carrito
          predicates:
            - Path=/api/carrito/**
          filters:
            - StripPrefix=2

        - id: ventas-service
          uri: lb://ms-ventas
          predicates:
            - Path=/api/ventas/**
          filters:
            - StripPrefix=2

        - id: citas-service
          uri: lb://ms-citas
          predicates:
            - Path=/api/citas/**
          filters:
            - StripPrefix=2

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true